// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalRVotacao.Models;

#nullable disable

namespace SignalRVotacao.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230310032029_Ajuste 2")]
    partial class Ajuste2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SignalRVotacao.Models.Participants", b =>
                {
                    b.Property<int>("ParticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParticName")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalVoto")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("ParticId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("SignalRVotacao.Models.Products", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("ProdName")
                        .HasColumnType("longtext");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ProdId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SignalRVotacao.Models.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Participant1Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Participant1Total")
                        .HasColumnType("int");

                    b.Property<int>("Participant2Id")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Participant2Total")
                        .HasColumnType("int");

                    b.Property<int>("Participant3Id")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("Participant3Total")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasColumnType("longtext");

                    b.HasKey("VoteId");

                    b.HasIndex("Participant1Id");

                    b.HasIndex("Participant2Id");

                    b.HasIndex("Participant3Id");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("SignalRVotacao.Models.Vote", b =>
                {
                    b.HasOne("SignalRVotacao.Models.Participants", "Participants")
                        .WithMany()
                        .HasForeignKey("Participant1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalRVotacao.Models.Participants", "Participants2")
                        .WithMany()
                        .HasForeignKey("Participant2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalRVotacao.Models.Participants", "Participants3")
                        .WithMany()
                        .HasForeignKey("Participant3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participants");

                    b.Navigation("Participants2");

                    b.Navigation("Participants3");
                });
#pragma warning restore 612, 618
        }
    }
}
